spring.application.name=helpdesk-backend

# SQLite DataSource
spring.datasource.url=jdbc:sqlite:helpdesk.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Deshabilita el anti-pattern Open Session in View
spring.jpa.open-in-view=false

# Puerto del servidor
server.port=8080

# JWT
app.jwt.secret=helpdesk-jwt-secret-key-muy-larga-para-hmac-sha256-minimo-256bits-segura
app.jwt.expiration=86400000
